package calculator

type IncomePerBracketAfterStandardDeductionMarriedJointCalculation SequenceCalculation

type IncomePerBracketAfterStandardDeductionMarriedJoint struct {
	AbstractIncomePerBracketAfterStandardDeductionCalculation
}

func NewIncomePerBracketAfterStandardDeductionMarriedJoint() IncomePerBracketAfterStandardDeductionMarriedJoint {
	return IncomePerBracketAfterStandardDeductionMarriedJoint{
		AbstractIncomePerBracketAfterStandardDeductionCalculation: NewAbstractIncomePerBracketAfterStandardDeduction(),
	}
}

func (c IncomePerBracketAfterStandardDeductionMarriedJoint) Calculate(model Model) []float64 {
	return c.AbstractIncomePerBracketAfterStandardDeductionCalculation.Calculate(model, model.MarriedJointTaxRates)
}

func (c IncomePerBracketAfterStandardDeductionMarriedJoint) CalculateRetirement(model Model) []float64 {
	return c.AbstractIncomePerBracketAfterStandardDeductionCalculation.CalculateRetirement(model, model.MarriedJointTaxRates)
}
