package calculator

type IncomePerBracketAfterStandardDeductionAndContributionsCalculation SequenceCalculation

type IncomePerBracketAfterStandardDeductionAndContributions struct {
	IncomePerBracketAfterStandardDeductionAndContributionsSingleCalculation
	IncomePerBracketAfterStandardDeductionAndContributionsMarriedJointCalculation
	IncomePerBracketAfterStandardDeductionAndContributionsMarriedSeparateCalculation
	IncomePerBracketAfterStandardDeductionAndContributionsHeadOfHouseholdCalculation
}

func NewIncomePerBracketAfterStandardDeductionAndContributions() IncomePerBracketAfterStandardDeductionAndContributions {
	return IncomePerBracketAfterStandardDeductionAndContributions{
		IncomePerBracketAfterStandardDeductionAndContributionsSingleCalculation:          NewIncomePerBracketAfterStandardDeductionAndContributionsSingle(),
		IncomePerBracketAfterStandardDeductionAndContributionsMarriedJointCalculation:    NewIncomePerBracketAfterStandardDeductionAndContributionsMarriedJoint(),
		IncomePerBracketAfterStandardDeductionAndContributionsMarriedSeparateCalculation: NewIncomePerBracketAfterStandardDeductionAndContributionsMarriedSeparate(),
		IncomePerBracketAfterStandardDeductionAndContributionsHeadOfHouseholdCalculation: NewIncomePerBracketAfterStandardDeductionAndContributionsHeadOfHousehold(),
	}
}

func (c IncomePerBracketAfterStandardDeductionAndContributions) CalculateTraditional(model *Model) []float64 {
	incomePerBracketAfterStandardDeductionAndContributionsSingle := c.IncomePerBracketAfterStandardDeductionAndContributionsSingleCalculation.CalculateTraditional(model)
	incomePerBracketAfterStandardDeductionAndContributionsMarriedJoint := c.IncomePerBracketAfterStandardDeductionAndContributionsMarriedJointCalculation.CalculateTraditional(model)
	incomePerBracketAfterStandardDeductionAndContributionsMarriedSeparate := c.IncomePerBracketAfterStandardDeductionAndContributionsMarriedSeparateCalculation.CalculateTraditional(model)
	incomePerBracketAfterStandardDeductionAndContributionsHeadOfHousehold := c.IncomePerBracketAfterStandardDeductionAndContributionsHeadOfHouseholdCalculation.CalculateTraditional(model)

	switch model.Input.CurrentFilingStatus {
	case "single":
		return incomePerBracketAfterStandardDeductionAndContributionsSingle
	case "married-joint":
		return incomePerBracketAfterStandardDeductionAndContributionsMarriedJoint
	case "married-seperate":
		return incomePerBracketAfterStandardDeductionAndContributionsMarriedSeparate
	case "head-of-household":
		return incomePerBracketAfterStandardDeductionAndContributionsHeadOfHousehold
	default:
		return incomePerBracketAfterStandardDeductionAndContributionsSingle
	}
}

func (c IncomePerBracketAfterStandardDeductionAndContributions) CalculateTraditionalRetirement(model *Model) []float64 {
	incomePerBracketAfterStandardDeductionAndContributionsSingle := c.IncomePerBracketAfterStandardDeductionAndContributionsSingleCalculation.CalculateTraditionalRetirement(model)
	incomePerBracketAfterStandardDeductionAndContributionsMarriedJoint := c.IncomePerBracketAfterStandardDeductionAndContributionsMarriedJointCalculation.CalculateTraditionalRetirement(model)
	incomePerBracketAfterStandardDeductionAndContributionsMarriedSeparate := c.IncomePerBracketAfterStandardDeductionAndContributionsMarriedSeparateCalculation.CalculateTraditionalRetirement(model)
	incomePerBracketAfterStandardDeductionAndContributionsHeadOfHousehold := c.IncomePerBracketAfterStandardDeductionAndContributionsHeadOfHouseholdCalculation.CalculateTraditionalRetirement(model)

	switch model.Input.RetirementFilingStatus {
	case "single":
		return incomePerBracketAfterStandardDeductionAndContributionsSingle
	case "married-joint":
		return incomePerBracketAfterStandardDeductionAndContributionsMarriedJoint
	case "married-seperate":
		return incomePerBracketAfterStandardDeductionAndContributionsMarriedSeparate
	case "head-of-household":
		return incomePerBracketAfterStandardDeductionAndContributionsHeadOfHousehold
	default:
		return incomePerBracketAfterStandardDeductionAndContributionsSingle
	}
}

func (c IncomePerBracketAfterStandardDeductionAndContributions) CalculateRoth(model *Model) []float64 {
	incomePerBracketAfterStandardDeductionAndContributionsSingle := c.IncomePerBracketAfterStandardDeductionAndContributionsSingleCalculation.CalculateRoth(model)
	incomePerBracketAfterStandardDeductionAndContributionsMarriedJoint := c.IncomePerBracketAfterStandardDeductionAndContributionsMarriedJointCalculation.CalculateRoth(model)
	incomePerBracketAfterStandardDeductionAndContributionsMarriedSeparate := c.IncomePerBracketAfterStandardDeductionAndContributionsMarriedSeparateCalculation.CalculateRoth(model)
	incomePerBracketAfterStandardDeductionAndContributionsHeadOfHousehold := c.IncomePerBracketAfterStandardDeductionAndContributionsHeadOfHouseholdCalculation.CalculateRoth(model)

	switch model.Input.CurrentFilingStatus {
	case "single":
		return incomePerBracketAfterStandardDeductionAndContributionsSingle
	case "married-joint":
		return incomePerBracketAfterStandardDeductionAndContributionsMarriedJoint
	case "married-seperate":
		return incomePerBracketAfterStandardDeductionAndContributionsMarriedSeparate
	case "head-of-household":
		return incomePerBracketAfterStandardDeductionAndContributionsHeadOfHousehold
	default:
		return incomePerBracketAfterStandardDeductionAndContributionsSingle
	}
}

func (c IncomePerBracketAfterStandardDeductionAndContributions) CalculateRothRetirement(model *Model) []float64 {
	incomePerBracketAfterStandardDeductionAndContributionsSingle := c.IncomePerBracketAfterStandardDeductionAndContributionsSingleCalculation.CalculateRothRetirement(model)
	incomePerBracketAfterStandardDeductionAndContributionsMarriedJoint := c.IncomePerBracketAfterStandardDeductionAndContributionsMarriedJointCalculation.CalculateRothRetirement(model)
	incomePerBracketAfterStandardDeductionAndContributionsMarriedSeparate := c.IncomePerBracketAfterStandardDeductionAndContributionsMarriedSeparateCalculation.CalculateRothRetirement(model)
	incomePerBracketAfterStandardDeductionAndContributionsHeadOfHousehold := c.IncomePerBracketAfterStandardDeductionAndContributionsHeadOfHouseholdCalculation.CalculateRothRetirement(model)

	switch model.Input.RetirementFilingStatus {
	case "single":
		return incomePerBracketAfterStandardDeductionAndContributionsSingle
	case "married-joint":
		return incomePerBracketAfterStandardDeductionAndContributionsMarriedJoint
	case "married-seperate":
		return incomePerBracketAfterStandardDeductionAndContributionsMarriedSeparate
	case "head-of-household":
		return incomePerBracketAfterStandardDeductionAndContributionsHeadOfHousehold
	default:
		return incomePerBracketAfterStandardDeductionAndContributionsSingle
	}
}
