package calculator

type IncomePerBracketAfterStandardDeductionAndContributionsSingleCalculation SequenceCalculation

type IncomePerBracketAfterStandardDeductionAndContributionsSingle struct {
	AbstractIncomePerBracketAfterStandardDeductionAndContributionsCalculation
}

func NewIncomePerBracketAfterStandardDeductionAndContributionsSingle() IncomePerBracketAfterStandardDeductionAndContributionsSingle {
	return IncomePerBracketAfterStandardDeductionAndContributionsSingle{
		AbstractIncomePerBracketAfterStandardDeductionAndContributionsCalculation: NewAbstractIncomePerBracketAfterStandardDeductionAndContributions(),
	}
}

func (c IncomePerBracketAfterStandardDeductionAndContributionsSingle) Calculate(model Model) []float64 {
	return c.AbstractIncomePerBracketAfterStandardDeductionAndContributionsCalculation.Calculate(model, model.SingleTaxRates)
}

func (c IncomePerBracketAfterStandardDeductionAndContributionsSingle) CalculateRetirement(model Model) []float64 {
	return c.AbstractIncomePerBracketAfterStandardDeductionAndContributionsCalculation.CalculateRetirement(model, model.SingleTaxRates)
}
