package calculator

type TaxesOwedPerBracketAfterStandardDeductionCalculation SequenceCalculation

type TaxesOwedPerBracketAfterStandardDeduction struct {
	TaxesOwedPerBracketAfterStandardDeductionSingleCalculation
	TaxesOwedPerBracketAfterStandardDeductionMarriedJointCalculation
	TaxesOwedPerBracketAfterStandardDeductionMarriedSeperateCalculation
	TaxesOwedPerBracketAfterStandardDeductionHeadOfHouseholdCalculation
}

func NewTaxesOwedPerBracketAfterStandardDeduction() TaxesOwedPerBracketAfterStandardDeduction {
	return TaxesOwedPerBracketAfterStandardDeduction{
		TaxesOwedPerBracketAfterStandardDeductionSingleCalculation:          NewTaxesOwedPerBracketAfterStandardDeductionSingle(),
		TaxesOwedPerBracketAfterStandardDeductionMarriedJointCalculation:    NewTaxesOwedPerBracketAfterStandardDeductionMarriedJoint(),
		TaxesOwedPerBracketAfterStandardDeductionMarriedSeperateCalculation: NewTaxesOwedPerBracketAfterStandardDeductionMarriedSeperate(),
		TaxesOwedPerBracketAfterStandardDeductionHeadOfHouseholdCalculation: NewTaxesOwedPerBracketAfterStandardDeductionHeadOfHousehold(),
	}
}

func (c TaxesOwedPerBracketAfterStandardDeduction) CalculateTraditional(model *Model) []float64 {
	taxesOwedPerBracketAfterStandardDeductionSingle := c.TaxesOwedPerBracketAfterStandardDeductionSingleCalculation.CalculateTraditional(model)
	taxesOwedPerBracketAfterStandardDeductionMarriedJoint := c.TaxesOwedPerBracketAfterStandardDeductionMarriedJointCalculation.CalculateTraditional(model)
	taxesOwedPerBracketAfterStandardDeductionMarriedSeperate := c.TaxesOwedPerBracketAfterStandardDeductionMarriedSeperateCalculation.CalculateTraditional(model)
	taxesOwedPerBracketAfterStandardDeductionHeadOfHousehold := c.TaxesOwedPerBracketAfterStandardDeductionHeadOfHouseholdCalculation.CalculateTraditional(model)

	switch model.Input.CurrentFilingStatus {
	case "single":
		return taxesOwedPerBracketAfterStandardDeductionSingle
	case "married-joint":
		return taxesOwedPerBracketAfterStandardDeductionMarriedJoint
	case "married-seperate":
		return taxesOwedPerBracketAfterStandardDeductionMarriedSeperate
	case "head-of-household":
		return taxesOwedPerBracketAfterStandardDeductionHeadOfHousehold
	default:
		return nil
	}
}

func (c TaxesOwedPerBracketAfterStandardDeduction) CalculateTraditionalRetirement(model *Model) []float64 {
	taxesOwedPerBracketAfterStandardDeductionSingle := c.TaxesOwedPerBracketAfterStandardDeductionSingleCalculation.CalculateTraditionalRetirement(model)
	taxesOwedPerBracketAfterStandardDeductionMarriedJoint := c.TaxesOwedPerBracketAfterStandardDeductionMarriedJointCalculation.CalculateTraditionalRetirement(model)
	taxesOwedPerBracketAfterStandardDeductionMarriedSeperate := c.TaxesOwedPerBracketAfterStandardDeductionMarriedSeperateCalculation.CalculateTraditionalRetirement(model)
	taxesOwedPerBracketAfterStandardDeductionHeadOfHousehold := c.TaxesOwedPerBracketAfterStandardDeductionHeadOfHouseholdCalculation.CalculateTraditionalRetirement(model)

	switch model.Input.RetirementFilingStatus {
	case "single":
		return taxesOwedPerBracketAfterStandardDeductionSingle
	case "married-joint":
		return taxesOwedPerBracketAfterStandardDeductionMarriedJoint
	case "married-seperate":
		return taxesOwedPerBracketAfterStandardDeductionMarriedSeperate
	case "head-of-household":
		return taxesOwedPerBracketAfterStandardDeductionHeadOfHousehold
	default:
		return nil
	}
}

func (c TaxesOwedPerBracketAfterStandardDeduction) CalculateRoth(model *Model) []float64 {
	taxesOwedPerBracketAfterStandardDeductionSingle := c.TaxesOwedPerBracketAfterStandardDeductionSingleCalculation.CalculateRoth(model)
	taxesOwedPerBracketAfterStandardDeductionMarriedJoint := c.TaxesOwedPerBracketAfterStandardDeductionMarriedJointCalculation.CalculateRoth(model)
	taxesOwedPerBracketAfterStandardDeductionMarriedSeperate := c.TaxesOwedPerBracketAfterStandardDeductionMarriedSeperateCalculation.CalculateRoth(model)
	taxesOwedPerBracketAfterStandardDeductionHeadOfHousehold := c.TaxesOwedPerBracketAfterStandardDeductionHeadOfHouseholdCalculation.CalculateRoth(model)

	switch model.Input.CurrentFilingStatus {
	case "single":
		return taxesOwedPerBracketAfterStandardDeductionSingle
	case "married-joint":
		return taxesOwedPerBracketAfterStandardDeductionMarriedJoint
	case "married-seperate":
		return taxesOwedPerBracketAfterStandardDeductionMarriedSeperate
	case "head-of-household":
		return taxesOwedPerBracketAfterStandardDeductionHeadOfHousehold
	default:
		return nil
	}
}

func (c TaxesOwedPerBracketAfterStandardDeduction) CalculateRothRetirement(model *Model) []float64 {
	taxesOwedPerBracketAfterStandardDeductionSingle := c.TaxesOwedPerBracketAfterStandardDeductionSingleCalculation.CalculateRothRetirement(model)
	taxesOwedPerBracketAfterStandardDeductionMarriedJoint := c.TaxesOwedPerBracketAfterStandardDeductionMarriedJointCalculation.CalculateRothRetirement(model)
	taxesOwedPerBracketAfterStandardDeductionMarriedSeperate := c.TaxesOwedPerBracketAfterStandardDeductionMarriedSeperateCalculation.CalculateRothRetirement(model)
	taxesOwedPerBracketAfterStandardDeductionHeadOfHousehold := c.TaxesOwedPerBracketAfterStandardDeductionHeadOfHouseholdCalculation.CalculateRothRetirement(model)

	switch model.Input.RetirementFilingStatus {
	case "single":
		return taxesOwedPerBracketAfterStandardDeductionSingle
	case "married-joint":
		return taxesOwedPerBracketAfterStandardDeductionMarriedJoint
	case "married-seperate":
		return taxesOwedPerBracketAfterStandardDeductionMarriedSeperate
	case "head-of-household":
		return taxesOwedPerBracketAfterStandardDeductionHeadOfHousehold
	default:
		return nil
	}
}
