package calculator

type TaxesOwedPerBracketAfterStandardDeductionAndContributionsCalculation SequenceCalculation

type TaxesOwedPerBracketAfterStandardDeductionAndContributions struct {
	TaxesOwedPerBracketAfterStandardDeductionAndContributionsSingleCalculation
	TaxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedJointCalculation
	TaxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedSeparateCalculation
	TaxesOwedPerBracketAfterStandardDeductionAndContributionsHeadOfHouseholdCalculation
}

func NewTaxesOwedPerBracketAfterStandardDeductionAndContributions() TaxesOwedPerBracketAfterStandardDeductionAndContributions {
	return TaxesOwedPerBracketAfterStandardDeductionAndContributions{
		TaxesOwedPerBracketAfterStandardDeductionAndContributionsSingleCalculation:          NewTaxesOwedPerBracketAfterStandardDeductionAndContributionsSingle(),
		TaxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedJointCalculation:    NewTaxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedJoint(),
		TaxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedSeparateCalculation: NewTaxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedSeparate(),
		TaxesOwedPerBracketAfterStandardDeductionAndContributionsHeadOfHouseholdCalculation: NewTaxesOwedPerBracketAfterStandardDeductionAndContributionsHeadOfHousehold(),
	}
}

func (c TaxesOwedPerBracketAfterStandardDeductionAndContributions) CalculateTraditional(model *Model) []float64 {
	taxesOwedPerBracketAfterStandardDeductionAndContributionsSingle := c.TaxesOwedPerBracketAfterStandardDeductionAndContributionsSingleCalculation.CalculateTraditional(model)
	taxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedJoint := c.TaxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedJointCalculation.CalculateTraditional(model)
	taxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedSeparate := c.TaxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedSeparateCalculation.CalculateTraditional(model)
	taxesOwedPerBracketAfterStandardDeductionAndContributionsHeadOfHousehold := c.TaxesOwedPerBracketAfterStandardDeductionAndContributionsHeadOfHouseholdCalculation.CalculateTraditional(model)

	switch model.Input.CurrentFilingStatus {
	case "single":
		return taxesOwedPerBracketAfterStandardDeductionAndContributionsSingle
	case "married-joint":
		return taxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedJoint
	case "married-separate":
		return taxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedSeparate
	case "head-of-household":
		return taxesOwedPerBracketAfterStandardDeductionAndContributionsHeadOfHousehold
	default:
		return taxesOwedPerBracketAfterStandardDeductionAndContributionsSingle
	}
}

func (c TaxesOwedPerBracketAfterStandardDeductionAndContributions) CalculateTraditionalRetirement(model *Model) []float64 {
	taxesOwedPerBracketAfterStandardDeductionAndContributionsSingle := c.TaxesOwedPerBracketAfterStandardDeductionAndContributionsSingleCalculation.CalculateTraditionalRetirement(model)
	taxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedJoint := c.TaxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedJointCalculation.CalculateTraditionalRetirement(model)
	taxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedSeparate := c.TaxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedSeparateCalculation.CalculateTraditionalRetirement(model)
	taxesOwedPerBracketAfterStandardDeductionAndContributionsHeadOfHousehold := c.TaxesOwedPerBracketAfterStandardDeductionAndContributionsHeadOfHouseholdCalculation.CalculateTraditionalRetirement(model)

	switch model.Input.RetirementFilingStatus {
	case "single":
		return taxesOwedPerBracketAfterStandardDeductionAndContributionsSingle
	case "married-joint":
		return taxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedJoint
	case "married-separate":
		return taxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedSeparate
	case "head-of-household":
		return taxesOwedPerBracketAfterStandardDeductionAndContributionsHeadOfHousehold
	default:
		return taxesOwedPerBracketAfterStandardDeductionAndContributionsSingle
	}
}

func (c TaxesOwedPerBracketAfterStandardDeductionAndContributions) CalculateRoth(model *Model) []float64 {
	taxesOwedPerBracketAfterStandardDeductionAndContributionsSingle := c.TaxesOwedPerBracketAfterStandardDeductionAndContributionsSingleCalculation.CalculateRoth(model)
	taxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedJoint := c.TaxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedJointCalculation.CalculateRoth(model)
	taxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedSeparate := c.TaxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedSeparateCalculation.CalculateRoth(model)
	taxesOwedPerBracketAfterStandardDeductionAndContributionsHeadOfHousehold := c.TaxesOwedPerBracketAfterStandardDeductionAndContributionsHeadOfHouseholdCalculation.CalculateRoth(model)

	switch model.Input.CurrentFilingStatus {
	case "single":
		return taxesOwedPerBracketAfterStandardDeductionAndContributionsSingle
	case "married-joint":
		return taxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedJoint
	case "married-separate":
		return taxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedSeparate
	case "head-of-household":
		return taxesOwedPerBracketAfterStandardDeductionAndContributionsHeadOfHousehold
	default:
		return taxesOwedPerBracketAfterStandardDeductionAndContributionsSingle
	}
}

func (c TaxesOwedPerBracketAfterStandardDeductionAndContributions) CalculateRothRetirement(model *Model) []float64 {
	taxesOwedPerBracketAfterStandardDeductionAndContributionsSingle := c.TaxesOwedPerBracketAfterStandardDeductionAndContributionsSingleCalculation.CalculateRothRetirement(model)
	taxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedJoint := c.TaxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedJointCalculation.CalculateRothRetirement(model)
	taxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedSeparate := c.TaxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedSeparateCalculation.CalculateRothRetirement(model)
	taxesOwedPerBracketAfterStandardDeductionAndContributionsHeadOfHousehold := c.TaxesOwedPerBracketAfterStandardDeductionAndContributionsHeadOfHouseholdCalculation.CalculateRothRetirement(model)

	switch model.Input.RetirementFilingStatus {
	case "single":
		return taxesOwedPerBracketAfterStandardDeductionAndContributionsSingle
	case "married-joint":
		return taxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedJoint
	case "married-separate":
		return taxesOwedPerBracketAfterStandardDeductionAndContributionsMarriedSeparate
	case "head-of-household":
		return taxesOwedPerBracketAfterStandardDeductionAndContributionsHeadOfHousehold
	default:
		return taxesOwedPerBracketAfterStandardDeductionAndContributionsSingle
	}
}
