package calculator

type TotalTaxesOwedAfterStandardDeductionAndContributionsCalculation Calculation

type TotalTaxesOwedAfterStandardDeductionAndContributions struct {
	TotalTaxesOwedAfterStandardDeductionAndContributionsSingleCalculation
	TotalTaxesOwedAfterStandardDeductionAndContributionsMarriedJointCalculation
	TotalTaxesOwedAfterStandardDeductionAndContributionsMarriedSeperateCalculation
	TotalTaxesOwedAfterStandardDeductionAndContributionsHeadOfHouseholdCalculation
}

func NewTotalTaxesOwedAfterStandardDeductionAndContributions() TotalTaxesOwedAfterStandardDeductionAndContributions {
	return TotalTaxesOwedAfterStandardDeductionAndContributions{
		TotalTaxesOwedAfterStandardDeductionAndContributionsSingleCalculation:          NewTotalTaxesOwedAfterStandardDeductionAndContributionsSingle(),
		TotalTaxesOwedAfterStandardDeductionAndContributionsMarriedJointCalculation:    NewTotalTaxesOwedAfterStandardDeductionAndContributionsMarriedJoint(),
		TotalTaxesOwedAfterStandardDeductionAndContributionsMarriedSeperateCalculation: NewTotalTaxesOwedAfterStandardDeductionAndContributionsMarriedSeperate(),
		TotalTaxesOwedAfterStandardDeductionAndContributionsHeadOfHouseholdCalculation: NewTotalTaxesOwedAfterStandardDeductionAndContributionsHeadOfHousehold(),
	}
}

func (c TotalTaxesOwedAfterStandardDeductionAndContributions) Calculate(model Model) float64 {
	totalTaxesOwedAfterStandardDeductionAndContributionsSingle := c.TotalTaxesOwedAfterStandardDeductionAndContributionsSingleCalculation.Calculate(model)
	totalTaxesOwedAfterStandardDeductionAndContributionsMarriedJoint := c.TotalTaxesOwedAfterStandardDeductionAndContributionsMarriedJointCalculation.Calculate(model)
	totalTaxesOwedAfterStandardDeductionAndContributionsMarriedSeperate := c.TotalTaxesOwedAfterStandardDeductionAndContributionsMarriedSeperateCalculation.Calculate(model)
	totalTaxesOwedAfterStandardDeductionAndContributionsHeadOfHousehold := c.TotalTaxesOwedAfterStandardDeductionAndContributionsHeadOfHouseholdCalculation.Calculate(model)

	switch model.Input.CurrentFilingStatus {
	case "single":
		return totalTaxesOwedAfterStandardDeductionAndContributionsSingle
	case "married-joint":
		return totalTaxesOwedAfterStandardDeductionAndContributionsMarriedJoint
	case "married-seperate":
		return totalTaxesOwedAfterStandardDeductionAndContributionsMarriedSeperate
	case "head-of-household":
		return totalTaxesOwedAfterStandardDeductionAndContributionsHeadOfHousehold
	default:
		return 0.0
	}
}

func (c TotalTaxesOwedAfterStandardDeductionAndContributions) CalculateRetirement(model Model) float64 {
	totalTaxesOwedAfterStandardDeductionAndContributionsSingle := c.TotalTaxesOwedAfterStandardDeductionAndContributionsSingleCalculation.CalculateRetirement(model)
	totalTaxesOwedAfterStandardDeductionAndContributionsMarriedJoint := c.TotalTaxesOwedAfterStandardDeductionAndContributionsMarriedJointCalculation.CalculateRetirement(model)
	totalTaxesOwedAfterStandardDeductionAndContributionsMarriedSeperate := c.TotalTaxesOwedAfterStandardDeductionAndContributionsMarriedSeperateCalculation.CalculateRetirement(model)
	totalTaxesOwedAfterStandardDeductionAndContributionsHeadOfHousehold := c.TotalTaxesOwedAfterStandardDeductionAndContributionsHeadOfHouseholdCalculation.CalculateRetirement(model)

	switch model.Input.RetirementFilingStatus {
	case "single":
		return totalTaxesOwedAfterStandardDeductionAndContributionsSingle
	case "married-joint":
		return totalTaxesOwedAfterStandardDeductionAndContributionsMarriedJoint
	case "married-seperate":
		return totalTaxesOwedAfterStandardDeductionAndContributionsMarriedSeperate
	case "head-of-household":
		return totalTaxesOwedAfterStandardDeductionAndContributionsHeadOfHousehold
	default:
		return 0.0
	}
}
