package calculator

type IncomePerBracketAfterStandardDeductionAndContributionsHeadOfHouseholdCalculation SequenceCalculation

type IncomePerBracketAfterStandardDeductionAndContributionsHeadOfHousehold struct {
	AbstractIncomePerBracketAfterStandardDeductionAndContributionsCalculation
}

func NewIncomePerBracketAfterStandardDeductionAndContributionsHeadOfHousehold() IncomePerBracketAfterStandardDeductionAndContributionsHeadOfHousehold {
	return IncomePerBracketAfterStandardDeductionAndContributionsHeadOfHousehold{
		AbstractIncomePerBracketAfterStandardDeductionAndContributionsCalculation: NewAbstractIncomePerBracketAfterStandardDeductionAndContributions(),
	}
}

func (c IncomePerBracketAfterStandardDeductionAndContributionsHeadOfHousehold) Calculate(model Model) []float64 {
	return c.AbstractIncomePerBracketAfterStandardDeductionAndContributionsCalculation.Calculate(model, model.HeadOfHouseholdTaxRates)
}

func (c IncomePerBracketAfterStandardDeductionAndContributionsHeadOfHousehold) CalculateRetirement(model Model) []float64 {
	return c.AbstractIncomePerBracketAfterStandardDeductionAndContributionsCalculation.CalculateRetirement(model, model.HeadOfHouseholdTaxRates)
}
