package calculator

type IncomePerBracketAfterStandardDeductionAndContributionsCalculation SequenceCalculation

type IncomePerBracketAfterStandardDeductionAndContributions struct {
	IncomePerBracketAfterStandardDeductionAndContributionsSingleCalculation
	IncomePerBracketAfterStandardDeductionAndContributionsMarriedJointCalculation
	IncomePerBracketAfterStandardDeductionAndContributionsMarriedSeperateCalculation
	IncomePerBracketAfterStandardDeductionAndContributionsHeadOfHouseholdCalculation
}

func NewIncomePerBracketAfterStandardDeductionAndContributions() IncomePerBracketAfterStandardDeductionAndContributions {
	return IncomePerBracketAfterStandardDeductionAndContributions{
		IncomePerBracketAfterStandardDeductionAndContributionsSingleCalculation:          NewIncomePerBracketAfterStandardDeductionAndContributionsSingle(),
		IncomePerBracketAfterStandardDeductionAndContributionsMarriedJointCalculation:    NewIncomePerBracketAfterStandardDeductionAndContributionsMarriedJoint(),
		IncomePerBracketAfterStandardDeductionAndContributionsMarriedSeperateCalculation: NewIncomePerBracketAfterStandardDeductionAndContributionsMarriedSeperate(),
		IncomePerBracketAfterStandardDeductionAndContributionsHeadOfHouseholdCalculation: NewIncomePerBracketAfterStandardDeductionAndContributionsHeadOfHousehold(),
	}
}

func (c IncomePerBracketAfterStandardDeductionAndContributions) Calculate(model Model) []float64 {
	incomePerBracketAfterStandardDeductionAndContributionsSingle := c.IncomePerBracketAfterStandardDeductionAndContributionsSingleCalculation.Calculate(model)
	incomePerBracketAfterStandardDeductionAndContributionsMarriedJoint := c.IncomePerBracketAfterStandardDeductionAndContributionsMarriedJointCalculation.Calculate(model)
	incomePerBracketAfterStandardDeductionAndContributionsMarriedSeperate := c.IncomePerBracketAfterStandardDeductionAndContributionsMarriedSeperateCalculation.Calculate(model)
	incomePerBracketAfterStandardDeductionAndContributionsHeadOfHousehold := c.IncomePerBracketAfterStandardDeductionAndContributionsHeadOfHouseholdCalculation.Calculate(model)

	switch model.Input.CurrentFilingStatus {
	case "single":
		return incomePerBracketAfterStandardDeductionAndContributionsSingle
	case "married-joint":
		return incomePerBracketAfterStandardDeductionAndContributionsMarriedJoint
	case "married-seperate":
		return incomePerBracketAfterStandardDeductionAndContributionsMarriedSeperate
	case "head-of-household":
		return incomePerBracketAfterStandardDeductionAndContributionsHeadOfHousehold
	default:
		return nil
	}
}

func (c IncomePerBracketAfterStandardDeductionAndContributions) CalculateRetirement(model Model) []float64 {
	incomePerBracketAfterStandardDeductionAndContributionsSingle := c.IncomePerBracketAfterStandardDeductionAndContributionsSingleCalculation.CalculateRetirement(model)
	incomePerBracketAfterStandardDeductionAndContributionsMarriedJoint := c.IncomePerBracketAfterStandardDeductionAndContributionsMarriedJointCalculation.CalculateRetirement(model)
	incomePerBracketAfterStandardDeductionAndContributionsMarriedSeperate := c.IncomePerBracketAfterStandardDeductionAndContributionsMarriedSeperateCalculation.CalculateRetirement(model)
	incomePerBracketAfterStandardDeductionAndContributionsHeadOfHousehold := c.IncomePerBracketAfterStandardDeductionAndContributionsHeadOfHouseholdCalculation.CalculateRetirement(model)

	switch model.Input.CurrentFilingStatus {
	case "single":
		return incomePerBracketAfterStandardDeductionAndContributionsSingle
	case "married-joint":
		return incomePerBracketAfterStandardDeductionAndContributionsMarriedJoint
	case "married-seperate":
		return incomePerBracketAfterStandardDeductionAndContributionsMarriedSeperate
	case "head-of-household":
		return incomePerBracketAfterStandardDeductionAndContributionsHeadOfHousehold
	default:
		return nil
	}
}
