package calculator

type IncomePerBracketAfterStandardDeductionHeadOfHouseholdCalculation SequenceCalculation

type IncomePerBracketAfterStandardDeductionHeadOfHousehold struct {
	AbstractIncomePerBracketAfterStandardDeductionCalculation
}

func NewIncomePerBracketAfterStandardDeductionHeadOfHousehold() IncomePerBracketAfterStandardDeductionHeadOfHousehold {
	return IncomePerBracketAfterStandardDeductionHeadOfHousehold{
		AbstractIncomePerBracketAfterStandardDeductionCalculation: NewAbstractIncomePerBracketAfterStandardDeduction(),
	}
}

func (c IncomePerBracketAfterStandardDeductionHeadOfHousehold) Calculate(model Model) []float64 {
	return c.AbstractIncomePerBracketAfterStandardDeductionCalculation.Calculate(model, model.HeadOfHouseholdTaxRates)
}

func (c IncomePerBracketAfterStandardDeductionHeadOfHousehold) CalculateRetirement(model Model) []float64 {
	return c.AbstractIncomePerBracketAfterStandardDeductionCalculation.CalculateRetirement(model, model.HeadOfHouseholdTaxRates)
}
