package calculator

type IncomePerBracketAfterStandardDeductionMarriedSeperateCalculation SequenceCalculation

type IncomePerBracketAfterStandardDeductionMarriedSeperate struct {
	AbstractIncomePerBracketAfterStandardDeductionCalculation
}

func NewIncomePerBracketAfterStandardDeductionMarriedSeperate() IncomePerBracketAfterStandardDeductionMarriedSeperate {
	return IncomePerBracketAfterStandardDeductionMarriedSeperate{
		AbstractIncomePerBracketAfterStandardDeductionCalculation: NewAbstractIncomePerBracketAfterStandardDeduction(),
	}
}

func (c IncomePerBracketAfterStandardDeductionMarriedSeperate) Calculate(model Model) []float64 {
	return c.AbstractIncomePerBracketAfterStandardDeductionCalculation.Calculate(model, model.MarriedSeperateTaxRates)
}

func (c IncomePerBracketAfterStandardDeductionMarriedSeperate) CalculateRetirement(model Model) []float64 {
	return c.AbstractIncomePerBracketAfterStandardDeductionCalculation.CalculateRetirement(model, model.MarriedSeperateTaxRates)
}
