# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Fri, 24 May 2024 00:32:07 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$oa1urIQkiyiWw7YOeYFo2eFzysyZk.npWQkb5nD14/xiK5yLeCxwi:admin:admin@admin:admin,user
